language: elixir
elixir: 1.7.4
otp_release: 21.1.1
branches:
  only:
    - master
before_install:
  - sudo apt-get install -y rpm2cpio wget
  - nvm install 10
install:
  - epmd -daemon
script: make travis
before_script: make travis-init
before_deploy: make travis-deploy
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: WAJHloLqvj1iQOXVm2Dn56ZXNCrnoWRl7erBKtEw4v0FOBY20+IuJ/FX9jqbZMu83iIn9ikMDPK9LEVpL/w1szcuimBQMFZ9uzQPLgImdnCpMdELu09IqBD50kE76sZGtRAiKh4PTpaZ+y/rEJDWi7W86DgOeNYWPF87SIsTqG2/t1AUiSYtcxOhvyZZf0B0ygYulW2fjrI034L2ty8HVJcgqinfGWiGQR6yAarYmejp1G55u2PbF5ehHf84A1c4BIpeVVJP3VlHikWMahN9zyXUiTSjUh/VFiMJPtirhZOvPRd6ZWAulng+z95DYyIcQFPEswA8d2U7cY2lM+Aw/UGahlrWOT1MKWRRhjSgW2TF/usaTpQXhFJoP640NGEYsLq/pkPAPaI5O0ZzrAqQ7ayTrXmgCEweE6cuhDXdOdDHyNkMu2HR1Vj1iALg/jx8K8UkmIFIS0QJpGf+gC+65LENnHlciYMGnSsDBkC3et2yj2u2Qv34l5AaNW8TFhIm44XHRs1Viyj7P9jIHJQyvhY86ARZM7XRJXFCGNFJ1Kg+Oi2GNXFblWvyv28eQcLEgqHYB9cSN/BLdGwtL9Kb3Iel5QdVC/jS7D7imn4SWeQYc7ec6HiwnMGSkhxO9YdMOGNJqIzk8II6HYcbLw9A5spBTNMHxN8fazp/KAqXmOQ=
    file_glob: true
    file: _build/releases/*
    on:
      repo: ArcBlock/abt-did-workshop
      branch: master
notifications:
  slack:
    secure: 
