[workshop]
path = "~/.workshop_app"

local_forge = "tcp://127.0.0.1:10120"

# the index db path
# sqlite://workshop.sqlite3 or postgres://postgres:postgres@localhost:5432/workshop
db = "sqlite://workshop.sqlite3"

# The port that workshop listens on.
port=9310