[workshop]
path = "~/.workshop"

local_forge = "tcp://127.0.0.1:27210"

# the index db path
# sqlite://workshop.sqlite3 or postgres://postgres:postgres@localhost:5432/workshop
db = "sqlite://workshop.sqlite3"

# The port that workshop listens on.
schema = "http"
host = "localhost"
port = 9309

[hyjal.application]
name = ""
description = ""
did = ""
sk = ""
pk = ""

# The application chain information
[hyjal.chain]
# The host and port to connect to the Forge Web of tha application chain.
host = "http://localhost"
port = 8210